name: nuli_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.5.4

# UI & animation
  lottie: ^3.3.2
  flutter_svg: ^2.2.1
  file_picker: ^10.3.3
  google_fonts: ^6.3.2

# State management
  get_it: ^8.2.0
  provider: ^6.1.5+1

# Network & API
  dio: ^5.9.0

# Video & Image
  image_picker: ^1.2.1
  video_player: ^2.10.1

#Navigater
  go_router: ^16.2.5

# Database & Storage
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  google_sign_in: ^6.2.1

  uuid: ^4.5.1

# Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/assets/images/
  - .env
